version: "3"
services:
  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: "digitalocean.com/php"
    container_name: app
    restart: unless-stopped
    tty: true
    depends_on:
      - server
      - redis
      - mysql
    environment:
      CONTAINER_ROLE: app
      SERVICE_NAME: app
      SERVICE_TAG: dev
      # Application
      APP_NAME: Laravel
      APP_ENV: local
      APP_KEY: "base64:EbCUbb8DKElCF1f1tF+PTrYdheNOpF0MVO+r0pXV+eY="
      APP_DEBUG: "true"
      APP_URL: http://localhost
      # Logging
      LOG_CHANNEL: stack
      # Database
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: your_mysql_root_password
      # Broadcast
      BROADCAST_DRIVER: log
      CACHE_DRIVER: redis
      QUEUE_DRIVER: redis
      QUEUE_CONNECTION: sync
      SESSION_DRIVER: redis
      SESSION_LIFETIME: 120
      # Redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./.data/logs:/var/www/storage/logs
      - ./.services/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - backend

  # Nginx Service
  server:
    image: nginx:alpine
    container_name: server
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "433:433"
    volumes:
      - ./:/var/www
      - ./.services/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - backend

  #MySQL Service
  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
    volumes:
      - ./.data/mysql:/var/lib/mysql
      - ./.services/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - backend

  # Redis Service
  redis:
    container_name: redis
    image: redis:4-alpine
    ports:
      - 16379:6379
    environment:
      SERVICE_TAGS: dev
      SERVICE_NAME: redis
    volumes:
      - ./.data/redis:/data
    networks:
      - backend

#Docker Networks
networks:
  backend:
    driver: bridge

#Volumes
volumes:
  redis:
    driver: "local"
  mysql:
    driver: local
