version: "3"
services:
  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: "digitalocean.com/php"
    container_name: app
    restart: unless-stopped
    tty: true
    depends_on:
      - server
      - redis
      - mysql
    environment:
      CONTAINER_ROLE: app
      SERVICE_NAME: app
      SERVICE_TAG: dev
      APP_ENV: local
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      QUEUE_DRIVER: redis
      REDIS_HOST: redis
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./.services/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - backend

  # Nginx Service
  server:
    image: nginx:alpine
    container_name: server
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "433:433"
    volumes:
      - ./:/var/www
      - ./.services/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - backend

  #MySQL Service
  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mysql:/var/lib/mysql
      - ./.services/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - backend

  # Redis Service
  redis:
    container_name: redis
    image: redis:4-alpine
    ports:
      - 16379:6379
    volumes:
      - ./.services/redis:/data
    networks:
      - backend

#Docker Networks
networks:
  backend:
    driver: bridge

#Volumes
volumes:
  redis:
    driver: "local"
  mysql:
    driver: local
